import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";
import NextAuthProvider from "@/components/AuthProvider/NextAuthProvider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Asian It INC ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div id="portal-root"></div>
        <NextTopLoader />
        <NextAuthProvider>
          {children}
        </NextAuthProvider>

        <Toaster />
      </body>
    </html>
  );
}
